### ISSUE TITLE
Feature Request: Support other LN software.

### ISSUE THREAD

**Issue by dscotese** [RooSoft/igniter#9]
"A Bitcoin lightning network LND node" could be "A Bitcoin lightning network LND node, c-lightning node, or Eclair node."

**Comment by RooSoft** [comment]
You're welcome to submit versions using other node software

**Comment by RooSoft** [comment]
While it would be a great idea to support all those, the aim here is to keep the script dead simple. There are usually at least one LND user in rings of fires who can run this script. Furthermore this issue is the only one mentioning `c-lightning` or `eclair` since igniter exists and nobody added comments to it.

For that reason, the project will thus stick to LND for now.

Thanks for the suggestion and have a great day!
